### ISSUE TITLE
Organise External Audit of DWYL's infoSec Controls to prep for ISO Certification

### ISSUE THREAD

**Issue by nelsonic** [dwyl/ISO-27001-2013-information-technology-security#17]
![image](https://cloud.githubusercontent.com/assets/194400/21483572/730f6e3e-cb7c-11e6-8deb-595c82f16e1d.png)

The "Next Step" (_after we've finished writing all the Controls, Policies and Procedures_) is to prepare ourselves to _apply_ for the ISO Certification. Once we have ISO certification we can display it as a "Badge" on our website and "bids" and clients like HL/SMG can tell _their_ stakeholders that their "Technology Partner" has the "_highest level_" of **ISO Standard Certification** for Information & Data Security & Privacy. 🔐  ✅ 

> ISO Certification will open up a ***whole new world*** of potential clients/partners to us. 
Which is why getting this done is _pivotal_ for our mission. ❤️ 

While we aren't _yet_ there with the implementation or documentation of our controls, but as soon as we are, we need to contact a 3rd party person to review them in preparation for the certification application.

Thankfully [Nelson](https://www.linkedin.com/in/nelsonic) has _worked_ with and maintains good (_pick up the phone and ask for advice_) connections to "_industry experts_" e.g:
+ Tatiane Zamboni (CISA + COBIT): https://www.linkedin.com/in/tatianezambonidownes
+ Rob Dighton (CISP): https://www.linkedin.com/in/robdighton
+ Ben Fargher (CISP): https://www.linkedin.com/in/benfargher
+ Umair Khattak (CISA): https://www.linkedin.com/in/umair-khattak-52787916
+ David Saunders (CISA): https://www.linkedin.com/in/david-saunders-a3452033

If anyone has _time_ to pickup on this task please comment below! thanks! 👍

**Comment by mndayizeye** [comment]
Hey , I thank to be in party of this online  or campony

**Comment by nelsonic** [comment]
Would still like to get this done some day. But not currently a priority. Closing.
